
services:
  acados:
    build:
      context: .
      dockerfile: dockerfile
    image: acados:latest
    container_name: acados
    volumes:
      - ./src/vehicle_nmpc:/workspace/vehicle_nmpc:ro
      - ./runs:/workspace/runs
    tty: true
    stdin_open: true
    working_dir: /workspace
    command:
      - /bin/bash
      - -lc
      - python3 -m vehicle_nmpc.run
