
services:
  acados:
    image: acados:latest
    build:
      context: .
      dockerfile: dockerfile
    container_name: acados
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src/vehicle_nmpc:/workspace/vehicle_nmpc:ro
      - ./logs:/workspace/logs
      - ./acados_codegen:/workspace/acados_codegen
    tty: true
    stdin_open: true
    working_dir: /workspace
    command: ["python3", "-m", "vehicle_nmpc.run"]
