[project]
name = "vehicle_nmpc"
version = "1.0.0"
authors = [
    { name = "Kirill Hitushkin", email = "khitushkink@mail.ru" }
]
description = "Nonlinear model predictive control for ground vehicles."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]

dependencies = [
    "casadi>=3.7.2",
    "colorlog>=6.10.1",
    "empy==3.3.4",
    "hydra-core>=1.3.2",
    "lark>=1.3.1",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "optuna>=4.9.0",
    "scipy>=1.17.1",
    "tqdm>=4.68.2",
]

[project.urls]
"Homepage" = "https://github.com/KirillHit/vehicle_nmpc"

[build-system]
requires = ["uv_build>=0.10.10,<0.11.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM812", # Conflicts with the formatter.
  "D203",   # Conflicts with D211.
  "D213",   # Conflicts with D212.
  "INP001",
  "PLC0415"
]
