name: acados_ocp
params:
  prediction_steps: 40
  prediction_horizon_time: 0.8
  artifacts_dir: ${runner.output_dir}/acados
  state_weights: [20.0, 20.0, 2.0]
  control_weights: [0.05, 0.05]
  control_lower_bounds: [-20.0, -20.0]
  control_upper_bounds: [20.0, 20.0]
  bounded_control_indices: [0, 1]
  qp_solver: PARTIAL_CONDENSING_HPIPM
  hessian_approx: GAUSS_NEWTON
  integrator_type: IRK
  sim_method_newton_iter: 10
  qp_solver_cond_n: 40
  translate_nls_cost_to_conl: true
