"""Tracked vehicle dynamic model implementation."""

from dataclasses import dataclass, field

import numpy as np
from acados_template import AcadosModel
from casadi import SX, cos, sin, sqrt, tanh, vertcat
from omegaconf import MISSING

from vehicle_nmpc.models import BaseModel, BaseModelConfig, ModelBundle, register_model
from vehicle_nmpc.utils.validation import as_vector, require_positive

_REGULARIZATION_EPSILON = 1e-6


@dataclass(frozen=True, kw_only=True, slots=True)
class DynamicModelSymbols:
    """Symbolic variables used by the tracked vehicle dynamic model."""

    x: SX
    xdot: SX
    u: SX
    pos_x: SX
    pos_y: SX
    yaw: SX
    vel_x: SX
    vel_y: SX
    yaw_rate: SX
    tau_l: SX
    tau_r: SX

    @classmethod
    def create(cls) -> "DynamicModelSymbols":
        """Create state, derivative, and control symbols."""
        pos_x = SX.sym("X")
        pos_y = SX.sym("Y")
        yaw = SX.sym("theta")
        vel_x = SX.sym("Vx")
        vel_y = SX.sym("Vy")
        yaw_rate = SX.sym("omega")

        x = vertcat(pos_x, pos_y, yaw, vel_x, vel_y, yaw_rate)

        tau_l = SX.sym("tau_l")
        tau_r = SX.sym("tau_r")
        u = vertcat(tau_l, tau_r)

        pos_x_dot = SX.sym("X_dot")
        pos_y_dot = SX.sym("Y_dot")
        yaw_dot = SX.sym("theta_dot")
        vel_x_dot = SX.sym("Vx_dot")
        vel_y_dot = SX.sym("Vy_dot")
        yaw_rate_dot = SX.sym("omega_dot")

        xdot = vertcat(pos_x_dot, pos_y_dot, yaw_dot, vel_x_dot, vel_y_dot, yaw_rate_dot)

        return cls(
            x=x,
            xdot=xdot,
            u=u,
            pos_x=pos_x,
            pos_y=pos_y,
            yaw=yaw,
            vel_x=vel_x,
            vel_y=vel_y,
            yaw_rate=yaw_rate,
            tau_l=tau_l,
            tau_r=tau_r,
        )


@dataclass(frozen=True, kw_only=True, slots=True)
class DynamicModelParameters:
    """Symbolic parameters used by the tracked vehicle dynamic model."""

    p: SX
    sprocket_radius: SX
    track_width: SX
    longitudinal_resistance: SX
    lateral_resistance: SX
    track_contact_length: SX
    gravity: SX
    mass: SX
    inertia: SX
    velocity_sign_epsilon: SX
    yaw_rate_sign_epsilon: SX

    @classmethod
    def create(cls) -> "DynamicModelParameters":
        """Create symbolic model parameters."""
        sprocket_radius = SX.sym("r")
        track_width = SX.sym("B")
        longitudinal_resistance = SX.sym("mu_l")
        lateral_resistance = SX.sym("mu_t")
        track_contact_length = SX.sym("l")
        gravity = SX.sym("g")
        mass = SX.sym("m")
        inertia = SX.sym("I")
        velocity_sign_epsilon = SX.sym("eps_v")
        yaw_rate_sign_epsilon = SX.sym("eps_omega")

        p = vertcat(
            sprocket_radius,
            track_width,
            longitudinal_resistance,
            lateral_resistance,
            track_contact_length,
            gravity,
            mass,
            inertia,
            velocity_sign_epsilon,
            yaw_rate_sign_epsilon,
        )

        return cls(
            p=p,
            sprocket_radius=sprocket_radius,
            track_width=track_width,
            longitudinal_resistance=longitudinal_resistance,
            lateral_resistance=lateral_resistance,
            track_contact_length=track_contact_length,
            gravity=gravity,
            mass=mass,
            inertia=inertia,
            velocity_sign_epsilon=velocity_sign_epsilon,
            yaw_rate_sign_epsilon=yaw_rate_sign_epsilon,
        )


@dataclass(frozen=True, kw_only=True, slots=True)
class TrackForces:
    """Forces and moments acting on the tracked vehicle."""

    left_drive_force: SX
    """Longitudinal drive force generated by the left track."""

    right_drive_force: SX
    """Longitudinal drive force generated by the right track."""

    vel_x_resistance_force: SX
    """Rolling resistance force opposing longitudinal motion."""

    yaw_rate_resistance_force: SX
    """Lateral resistance force induced by yaw motion."""

    vel_y_resistance_force: SX
    """Lateral resistance force opposing body-frame lateral velocity."""

    drive_moment: SX
    """Yaw moment generated by the difference in track drive forces."""

    resistance_moment: SX
    """Yaw resistance moment from lateral track-ground interaction."""

    centrifugal_acceleration: SX
    """Centrifugal acceleration term used in lateral force calculations."""

    sin_beta: SX
    """Sine of the side-slip angle approximation."""

    cos_beta: SX
    """Cosine of the side-slip angle approximation."""

    rotation_center_offset: SX
    """Longitudinal offset of the instantaneous rotation center."""


@register_model("tracked_veh_dynamic")
class TrackedVehDynamicModel(BaseModel):
    """Dynamic skid-steering tracked vehicle model."""

    @dataclass(frozen=True, kw_only=True, slots=True)
    class Config(BaseModelConfig):
        """Tracked vehicle dynamic model configuration."""

        sprocket_radius: float = MISSING
        """Drive sprocket radius."""

        track_width: float = MISSING
        """Distance between left and right track center lines."""

        track_contact_length: float = MISSING
        """Length of the track contact patch."""

        longitudinal_resistance: float = MISSING
        """Coefficient of longitudinal resistance μ_l."""

        lateral_resistance: float = MISSING
        """Coefficient of transverse resistance μ_t."""

        gravity: float = 9.81
        """Acceleration due to gravity."""

        mass: float = MISSING
        """Vehicle mass m."""

        inertia: float = MISSING
        """Moment of inertia I_z."""

        velocity_sign_epsilon: float = 0.05
        """Smoothing scale for longitudinal velocity sign."""

        yaw_rate_sign_epsilon: float = 0.05
        """Smoothing scale for yaw-rate sign."""

        x0: list[float] = field(default_factory=lambda: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        """Default initial state [X, Y, theta, Vx, Vy, omega]."""

        def __post_init__(self) -> None:
            """Validate physical model parameters."""
            require_positive("sprocket_radius", self.sprocket_radius)
            require_positive("track_width", self.track_width)
            require_positive("track_contact_length", self.track_contact_length)
            require_positive("longitudinal_resistance", self.longitudinal_resistance)
            require_positive("lateral_resistance", self.lateral_resistance)
            require_positive("gravity", self.gravity)
            require_positive("mass", self.mass)
            require_positive("inertia", self.inertia)
            require_positive("velocity_sign_epsilon", self.velocity_sign_epsilon)
            require_positive("yaw_rate_sign_epsilon", self.yaw_rate_sign_epsilon)

    def __init__(self, cfg: Config) -> None:
        """Initialize the model with the provided configuration."""
        super().__init__(cfg)

    def build(self) -> ModelBundle:
        """Build and return the Acados model bundle."""
        symbols = DynamicModelSymbols.create()
        parameters = DynamicModelParameters.create()
        forces = self._track_forces(symbols, parameters)
        f_expl = self._explicit_dynamics(symbols, parameters, forces)
        f_impl = symbols.xdot - f_expl

        model = AcadosModel()
        model.f_impl_expr = f_impl
        model.f_expl_expr = f_expl
        model.x = symbols.x
        model.xdot = symbols.xdot
        model.u = symbols.u
        model.p = parameters.p
        model.name = "tracked_veh_dynamic"
        self._set_labels(model)

        return ModelBundle(
            model=model,
            nx=6,
            nu=2,
            np=10,
            p0=self._parameter_values(),
            x0=as_vector("x0", self._cfg.x0, 6),
        )

    def _track_forces(
        self,
        symbols: DynamicModelSymbols,
        parameters: DynamicModelParameters,
    ) -> TrackForces:
        """Compute drive, resistance, lateral, and yaw moments."""
        eps = _REGULARIZATION_EPSILON
        lateral_denom = 2.0 * parameters.lateral_resistance * parameters.gravity + eps
        tan_beta = parameters.track_contact_length * symbols.yaw_rate * symbols.yaw_rate
        tan_beta /= lateral_denom
        cos_beta = 1.0 / sqrt(1.0 + tan_beta * tan_beta)
        sin_beta = tan_beta * cos_beta
        raw_rotation_center_offset = (
            parameters.track_contact_length * symbols.vel_x * symbols.yaw_rate / lateral_denom
        )
        max_rotation_center_offset = 0.5 * parameters.track_contact_length
        rotation_center_offset = max_rotation_center_offset * tanh(
            raw_rotation_center_offset / (max_rotation_center_offset + eps)
        )

        speed = sqrt(symbols.vel_x * symbols.vel_x + symbols.vel_y * symbols.vel_y + eps * eps)
        centrifugal_acceleration = speed * symbols.yaw_rate
        yaw_rate_direction = self._smooth_sign(symbols.yaw_rate, parameters.yaw_rate_sign_epsilon)
        vel_x_direction = self._smooth_sign(symbols.vel_x, parameters.velocity_sign_epsilon)
        vel_y_direction = self._smooth_sign(
            symbols.vel_y,
            parameters.velocity_sign_epsilon,
        )

        left_drive_force = symbols.tau_l / parameters.sprocket_radius
        right_drive_force = symbols.tau_r / parameters.sprocket_radius

        vel_x_resistance_force = (
            parameters.longitudinal_resistance
            * parameters.mass
            * parameters.gravity
            * vel_x_direction
        )
        yaw_rate_resistance_force = (
            yaw_rate_direction
            * 2.0
            * parameters.lateral_resistance
            * parameters.mass
            * parameters.gravity
            * rotation_center_offset
            / (parameters.track_contact_length + eps)
        )
        vel_y_resistance_force = (
            -parameters.lateral_resistance * parameters.mass * parameters.gravity * vel_y_direction
        )
        drive_moment = (right_drive_force - left_drive_force) * parameters.track_width / 2.0
        resistance_moment = (
            yaw_rate_direction
            * parameters.lateral_resistance
            * parameters.mass
            * parameters.gravity
            / (parameters.track_contact_length + eps)
            * (
                (parameters.track_contact_length * parameters.track_contact_length) / 4.0
                - rotation_center_offset * rotation_center_offset
            )
        )

        return TrackForces(
            left_drive_force=left_drive_force,
            right_drive_force=right_drive_force,
            vel_x_resistance_force=vel_x_resistance_force,
            yaw_rate_resistance_force=yaw_rate_resistance_force,
            vel_y_resistance_force=vel_y_resistance_force,
            drive_moment=drive_moment,
            resistance_moment=resistance_moment,
            centrifugal_acceleration=centrifugal_acceleration,
            sin_beta=sin_beta,
            cos_beta=cos_beta,
            rotation_center_offset=rotation_center_offset,
        )

    def _explicit_dynamics(
        self,
        symbols: DynamicModelSymbols,
        parameters: DynamicModelParameters,
        forces: TrackForces,
    ) -> SX:
        """Build the explicit state derivative expression."""
        return vertcat(
            cos(symbols.yaw) * symbols.vel_x - sin(symbols.yaw) * symbols.vel_y,
            sin(symbols.yaw) * symbols.vel_x + cos(symbols.yaw) * symbols.vel_y,
            symbols.yaw_rate,
            (
                forces.left_drive_force
                + forces.right_drive_force
                - parameters.mass * forces.centrifugal_acceleration * forces.sin_beta
                - forces.vel_x_resistance_force
            )
            / parameters.mass,
            (
                forces.yaw_rate_resistance_force
                + forces.vel_y_resistance_force
                - parameters.mass * forces.centrifugal_acceleration * forces.cos_beta
            )
            / parameters.mass,
            (
                forces.drive_moment
                - forces.resistance_moment
                + parameters.mass
                * forces.centrifugal_acceleration
                * forces.rotation_center_offset
                * forces.cos_beta
            )
            / parameters.inertia,
        )

    def _set_labels(self, model: AcadosModel) -> None:
        """Set plotting labels on the Acados model."""
        model.x_labels = [
            "$X$ [m]",
            "$Y$ [m]",
            r"$\theta$ [rad]",
            "$V_x$ [m/s]",
            "$V_y$ [m/s]",
            r"$\omega$ [rad/s]",
        ]
        model.u_labels = [r"$\tau_l$ [N m]", r"$\tau_r$ [N m]"]
        model.t_label = "$t$ [s]"

    def _parameter_values(self) -> np.ndarray:
        """Return default numeric values for the symbolic parameter vector."""
        return as_vector(
            "p0",
            [
                self._cfg.sprocket_radius,
                self._cfg.track_width,
                self._cfg.longitudinal_resistance,
                self._cfg.lateral_resistance,
                self._cfg.track_contact_length,
                self._cfg.gravity,
                self._cfg.mass,
                self._cfg.inertia,
                self._cfg.velocity_sign_epsilon,
                self._cfg.yaw_rate_sign_epsilon,
            ],
            10,
        )

    def _smooth_sign(self, value: SX, eps: SX) -> SX:
        """Return a differentiable sign approximation."""
        return value / sqrt(value * value + eps * eps)
