defaults:
  - base_config
  - model: tracked_veh_dynamic
  - problem: acados_ocp_dynamic
  - sim: acados_sim
  - runner: base
  - controller: rti_nmpc
  - optuna: base
  - trajectories: tracking_suite
  - override hydra/job_logging: colorlog
  - _self_
    
hydra:
  run:
    dir: runs/${runner.experiment_name}/${model.name}/${now:%Y-%m-%d_%H-%M-%S}_${controller.name}
  sweep:
    dir: runs/${runner.experiment_name}/${model.name}/${now:%Y-%m-%d_%H-%M-%S}_${controller.name}
    subdir: ${hydra.job.num}
