defaults:
  - base_config
  - model: tracked_veh_kinematic
  - executor: base
  - controller: rti_nmpc
  - override hydra/job_logging: colorlog
  - _self_
    
hydra:
  run:
    dir: logs/${executor.experiment_name}/${now:%Y-%m-%d_%H-%M-%S}_${model.name}_${controller.name}
  sweep:
    dir: logs/${executor.experiment_name}/${now:%Y-%m-%d_%H-%M-%S}_${model.name}_${controller.name}
    subdir: ${hydra.job.num}