defaults:
  - base_config
  - model: tracked_veh_kinematic
  - runner: base
  - controller: rti_nmpc
  - override hydra/job_logging: colorlog
  - _self_
    
hydra:
  run:
    dir: runs/${runner.experiment_name}/${model.name}/${now:%Y-%m-%d_%H-%M-%S}_${controller.name}
  sweep:
    dir: runs/${runner.experiment_name}/${model.name}/${now:%Y-%m-%d_%H-%M-%S}_${controller.name}
    subdir: ${hydra.job.num}