name: tracked_veh_dynamic
params:
  sprocket_radius: 0.3
  track_width: 0.86
  track_contact_length: 1.2
  longitudinal_resistance: 0.04
  lateral_resistance: 0.8
  gravity: 9.81
  mass: 350.0
  inertia: 100.0
  velocity_sign_epsilon: 0.1
  yaw_rate_sign_epsilon: 0.1
