name: tracked_veh_kinematic
params:
  sprocket_radius: 0.105
  track_width: 0.84
  track_contact_length: 1.05215
  left_slip: 0.05
  right_slip: 0.05
  lateral_resistance: 0.8
  gravity: 9.81
  yaw_rate_sign_epsilon: 0.1
  x0: [0.0, 0.0, 0.0]
