name: Lint

on:
  push:
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Ruff lint check
        run: uvx ruff check .

      - name: Ruff format check
        run: uvx ruff format --check .
